spring.application.name=reserva-salas

spring.datasource.url=jdbc:postgresql://localhost:5432/reserva-salas
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
